FROM node:15.2.0-alpine3.12
RUN apk update && apk add --virtual build-dependencies build-base gcc wget git openssh
WORKDIR /usr/src/app

COPY ./package.json .

EXPOSE 3010
ENTRYPOINT npm install && npm run dev
