version: "2"
services:
  fuel-tracker-db:
    container_name: fuel-tracker-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "database"
      MYSQL_USER: "database"
      MYSQL_PASSWORD: "toor"
      MYSQL_ROOT_PASSWORD: "toor"
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - fuel-tracker-db-data:/var/lib/mysql
    networks:
      inner:
        aliases:
          - fuel-tracker-db
  fuel-tracker:
    container_name: fuel-tracker
    build:
      context: ./fuel-tracker
      dockerfile: Dockerfile.development
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - fuel-tracker-db
    volumes:
      - "./fuel-tracker/:/usr/src/app"
      - "~/.ssh:/root/.ssh"
    networks:
      inner:
        aliases:
          - fuel-tracker
  fuel-tracker-frontend:
    container_name: fuel-tracker-frontend
    build:
      context: ./fuel-tracker-frontend
      dockerfile: Dockerfile.development
    volumes:
      - "./fuel-tracker-frontend:/usr/src/app"
    expose:
      - "4200"
    ports:
      - "3002:3002" # Port mapping
      - "4200:4200"
    depends_on:
      - fuel-tracker
    networks:
      inner:
        aliases:
          - fuel-tracker-frontend
networks:
  inner: {}
volumes:
  fuel-tracker-db-data: {}
